#!/usr/bin/env bash
set -euo pipefail

DOMAIN=""
TUNNEL_SUBDOMAIN="tunnel"
UPSTREAM="127.0.0.1:8080"
ENABLE_WILDCARD=1
ENABLE_TLS=1
EMAIL=""
SKIP_INSTALL=0
SKIP_BACKUP=0

usage() {
  cat <<'EOF'
Unified Nginx tunnel bootstrap (install + fix + configure).

Usage:
  sudo bash scripts/bootstrap-tunnel-nginx.sh --domain faiezwaseem.site [options]

Options:
  --domain <domain>              Base domain (required)
  --tunnel-subdomain <name>      Control plane subdomain (default: tunnel)
  --upstream <host:port>         Bun upstream (default: 127.0.0.1:8080)
  --no-wildcard                  Disable wildcard data-plane vhost (*.domain)
  --no-tls                       Skip certbot + HTTPS config
  --email <email>                Email for certbot (optional)
  --skip-install                 Skip apt install for nginx/certbot packages
  --skip-backup                  Skip /etc/nginx backup
  -h, --help                     Show help

What it does:
  1) Installs nginx + certbot plugin (unless --skip-install)
  2) Backs up /etc/nginx (unless --skip-backup)
  3) Removes conflicting tunnel host from default.conf safely
  4) Writes isolated tunnel config in sites-available
  5) Tests and reloads nginx
  6) Optionally obtains cert (certonly) and enables HTTPS for tunnel host
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      DOMAIN="${2:-}"
      shift 2
      ;;
    --tunnel-subdomain)
      TUNNEL_SUBDOMAIN="${2:-}"
      shift 2
      ;;
    --upstream)
      UPSTREAM="${2:-}"
      shift 2
      ;;
    --no-wildcard)
      ENABLE_WILDCARD=0
      shift
      ;;
    --no-tls)
      ENABLE_TLS=0
      shift
      ;;
    --email)
      EMAIL="${2:-}"
      shift 2
      ;;
    --skip-install)
      SKIP_INSTALL=1
      shift
      ;;
    --skip-backup)
      SKIP_BACKUP=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$DOMAIN" ]]; then
  echo "Error: --domain is required." >&2
  usage
  exit 1
fi

if [[ $EUID -ne 0 ]]; then
  echo "Error: run with sudo/root." >&2
  exit 1
fi

if ! [[ "$UPSTREAM" =~ ^[a-zA-Z0-9\.\-]+:[0-9]{1,5}$ ]]; then
  echo "Error: --upstream must be host:port (got '$UPSTREAM')." >&2
  exit 1
fi

TUNNEL_HOST="${TUNNEL_SUBDOMAIN}.${DOMAIN}"
TS="$(date +%F-%H%M%S)"
CONF_AVAIL="/etc/nginx/sites-available/${TUNNEL_HOST}.conf"
CONF_ENABLED="/etc/nginx/sites-enabled/${TUNNEL_HOST}.conf"
DEFAULT_CONF="/etc/nginx/sites-enabled/default.conf"
CERT_FULLCHAIN="/etc/letsencrypt/live/${TUNNEL_HOST}/fullchain.pem"
CERT_PRIVKEY="/etc/letsencrypt/live/${TUNNEL_HOST}/privkey.pem"

write_default_conf_safe() {
  cat > "$DEFAULT_CONF" <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 444;
}
EOF
}

write_tunnel_conf_http() {
  cat > "$CONF_AVAIL" <<EOF
# Auto-generated by bootstrap-tunnel-nginx.sh

server {
    listen 80;
    listen [::]:80;
    server_name ${TUNNEL_HOST};

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF

  if [[ $ENABLE_WILDCARD -eq 1 ]]; then
    cat >> "$CONF_AVAIL" <<EOF

server {
    listen 80;
    listen [::]:80;
    server_name .${DOMAIN};

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF
  fi
}

write_tunnel_conf_https() {
  cat > "$CONF_AVAIL" <<EOF
# Auto-generated by bootstrap-tunnel-nginx.sh

server {
    listen 80;
    listen [::]:80;
    server_name ${TUNNEL_HOST};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${TUNNEL_HOST};

    ssl_certificate ${CERT_FULLCHAIN};
    ssl_certificate_key ${CERT_PRIVKEY};

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF

  if [[ $ENABLE_WILDCARD -eq 1 ]]; then
    cat >> "$CONF_AVAIL" <<EOF

server {
    listen 80;
    listen [::]:80;
    server_name .${DOMAIN};

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF
  fi
}

cleanup_conflicts() {
  local conflicts
  conflicts=$(grep -Rsl --include='*.conf' "server_name[[:space:]].*${TUNNEL_HOST}" /etc/nginx/sites-enabled || true)
  if [[ -z "$conflicts" ]]; then
    return
  fi

  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    [[ "$f" == "$CONF_ENABLED" ]] && continue

    if [[ "$f" == "$DEFAULT_CONF" ]]; then
      cp -a "$DEFAULT_CONF" "${DEFAULT_CONF}.bak.${TS}"
      write_default_conf_safe
      continue
    fi

    if [[ -L "$f" ]]; then
      mv "$f" "${f}.disabled.${TS}"
      echo "Disabled conflicting site symlink: $f"
    else
      echo "Error: conflicting host found in non-symlink file: $f" >&2
      echo "Please remove '${TUNNEL_HOST}' from that file and rerun." >&2
      exit 1
    fi
  done <<< "$conflicts"
}

if [[ $SKIP_INSTALL -eq 0 ]]; then
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y nginx certbot python3-certbot-nginx
fi

if [[ ! -d /etc/nginx ]]; then
  echo "Error: /etc/nginx not found." >&2
  exit 1
fi

if [[ $SKIP_BACKUP -eq 0 ]]; then
  BACKUP_PATH="/etc/nginx.backup.${TS}"
  echo "Backing up /etc/nginx -> ${BACKUP_PATH}"
  cp -a /etc/nginx "$BACKUP_PATH"
fi

mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled
cleanup_conflicts
write_tunnel_conf_http
ln -sf "$CONF_AVAIL" "$CONF_ENABLED"

nginx -t
systemctl reload nginx || systemctl restart nginx

if [[ $ENABLE_TLS -eq 1 ]]; then
  if [[ -n "$EMAIL" ]]; then
    certbot certonly --nginx -d "$TUNNEL_HOST" --non-interactive --agree-tos -m "$EMAIL" --keep-until-expiring
  else
    certbot certonly --nginx -d "$TUNNEL_HOST" --non-interactive --agree-tos --register-unsafely-without-email --keep-until-expiring
  fi

  if [[ ! -f "$CERT_FULLCHAIN" || ! -f "$CERT_PRIVKEY" ]]; then
    echo "Error: cert files missing after certbot." >&2
    exit 1
  fi

  write_tunnel_conf_https
  nginx -t
  systemctl reload nginx || systemctl restart nginx
fi

echo
echo "Done."
echo "Control host: ${TUNNEL_HOST}"
echo "Upstream: ${UPSTREAM}"
if [[ $ENABLE_WILDCARD -eq 1 ]]; then
  echo "Wildcard enabled: *.${DOMAIN}"
else
  echo "Wildcard disabled."
fi
if [[ $ENABLE_TLS -eq 1 ]]; then
  echo "HTTPS enabled for ${TUNNEL_HOST}."
  echo "Wildcard HTTPS requires DNS-challenge cert for *.${DOMAIN}."
fi

