#!/usr/bin/env bash
set -euo pipefail

DOMAIN=""
TUNNEL_SUBDOMAIN="tunnel"
UPSTREAM="127.0.0.1:8080"
ENABLE_WILDCARD=1
RUN_CERTBOT=0
EMAIL=""
SKIP_BACKUP=0

usage() {
  cat <<'EOF'
Auto-configure Nginx for Bun tunnel server.

Usage:
  sudo bash scripts/configure-nginx-tunnel.sh --domain faiezwaseem.site [options]

Options:
  --domain <domain>              Base domain (required), e.g. faiezwaseem.site
  --tunnel-subdomain <name>      Control-plane subdomain (default: tunnel)
  --upstream <host:port>         Bun upstream (default: 127.0.0.1:8080)
  --no-wildcard                  Do not create wildcard data-plane vhost
  --certbot                      Run certbot for tunnel subdomain after nginx reload
  --email <email>                Certbot email (optional)
  --skip-backup                  Skip /etc/nginx backup
  -h, --help                     Show this help

Examples:
  sudo bash scripts/configure-nginx-tunnel.sh --domain faiezwaseem.site
  sudo bash scripts/configure-nginx-tunnel.sh --domain faiezwaseem.site --certbot
  sudo bash scripts/configure-nginx-tunnel.sh --domain example.com --tunnel-subdomain edge --upstream 127.0.0.1:9000
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      DOMAIN="${2:-}"
      shift 2
      ;;
    --tunnel-subdomain)
      TUNNEL_SUBDOMAIN="${2:-}"
      shift 2
      ;;
    --upstream)
      UPSTREAM="${2:-}"
      shift 2
      ;;
    --no-wildcard)
      ENABLE_WILDCARD=0
      shift
      ;;
    --certbot)
      RUN_CERTBOT=1
      shift
      ;;
    --email)
      EMAIL="${2:-}"
      shift 2
      ;;
    --skip-backup)
      SKIP_BACKUP=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$DOMAIN" ]]; then
  echo "Error: --domain is required." >&2
  usage
  exit 1
fi

if [[ $EUID -ne 0 ]]; then
  echo "Error: run as root (use sudo)." >&2
  exit 1
fi

if ! command -v nginx >/dev/null 2>&1; then
  echo "Error: nginx is not installed." >&2
  exit 1
fi

if ! [[ "$UPSTREAM" =~ ^[a-zA-Z0-9\.\-]+:[0-9]{1,5}$ ]]; then
  echo "Error: --upstream must look like host:port (got '$UPSTREAM')." >&2
  exit 1
fi

TUNNEL_HOST="${TUNNEL_SUBDOMAIN}.${DOMAIN}"
CONFIG_PATH="/etc/nginx/sites-available/${TUNNEL_HOST}.conf"
SYMLINK_PATH="/etc/nginx/sites-enabled/${TUNNEL_HOST}.conf"

if [[ $SKIP_BACKUP -eq 0 ]]; then
  BACKUP_PATH="/etc/nginx.backup.$(date +%F-%H%M%S)"
  echo "Backing up /etc/nginx -> ${BACKUP_PATH}"
  cp -a /etc/nginx "${BACKUP_PATH}"
fi

echo "Writing ${CONFIG_PATH}"
cat > "${CONFIG_PATH}" <<EOF
# Auto-generated by configure-nginx-tunnel.sh

# Control plane: client websocket + API
server {
    listen 80;
    listen [::]:80;
    server_name ${TUNNEL_HOST};

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF

if [[ $ENABLE_WILDCARD -eq 1 ]]; then
  cat >> "${CONFIG_PATH}" <<EOF

# Data plane: wildcard public subdomains
server {
    listen 80;
    listen [::]:80;
    server_name .${DOMAIN};

    location / {
        proxy_pass http://${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF
fi

ln -sf "${CONFIG_PATH}" "${SYMLINK_PATH}"

echo "Testing nginx config..."
nginx -t
echo "Reloading nginx..."
systemctl reload nginx

echo
echo "Nginx tunnel config applied successfully."
echo "Control plane host: ${TUNNEL_HOST}"
echo "Upstream: ${UPSTREAM}"
if [[ $ENABLE_WILDCARD -eq 1 ]]; then
  echo "Wildcard vhost enabled for: *.${DOMAIN}"
else
  echo "Wildcard vhost disabled."
fi

if [[ $RUN_CERTBOT -eq 1 ]]; then
  if ! command -v certbot >/dev/null 2>&1; then
    echo "Error: certbot not installed. Install certbot and rerun with --certbot." >&2
    exit 1
  fi

  echo "Requesting/installing certificate for ${TUNNEL_HOST}..."
  if [[ -n "$EMAIL" ]]; then
    certbot --nginx -d "${TUNNEL_HOST}" --non-interactive --agree-tos -m "${EMAIL}"
  else
    certbot --nginx -d "${TUNNEL_HOST}"
  fi

  echo "Certificate workflow finished for ${TUNNEL_HOST}."
  echo "For wildcard TLS (*.${DOMAIN}), use DNS challenge certificates."
fi

